# Generated by Django 4.2.11 on 2025-09-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seat_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('movie', 'seat_number')},
        ),
    ]
